name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup CMake
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake

    - name: Check if build directory exists
      run: |
        if [ ! -d "build" ]; then
          mkdir build
        fi

    - name: Build project
      run: |
        cd build
        cmake ..
        make

  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: 'recursive' # 如果你的项目使用了子模块，确保子模块也被检出

    - name: Setup CMake
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake

    - name: Check if build directory exists
      run: |
        if [ ! -d "build" ]; then
          mkdir build
        fi

    - name: Build project
      run: |
        cd build
        cmake ..
        make

    - name: Run tests
      run: |
        cd build
        ./GSTest
