name: C++ CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake g++ make
    - name: Configure CMake
      run: |
        if [ ! -d "/home/runner/work/Code-Development/Code-Development/build" ]; then
          mkdir /home/runner/work/Code-Development/Code-Development/build
        fi
        cd /home/runner/work/Code-Development/Code-Development/build
        cmake -S /home/runner/work/Code-Development/Code-Development -B .
    - name: Build
      run: cmake --build /home/runner/work/Code-Development/Code-Development/build
    - name: Run tests
      run: /home/runner/work/Code-Development/Code-Development/build/GSTest
